### PR TITLE
Milestone 2

### PR DESCRIPTION
**Pull request by Murodjon000**
### Hi TSE 🙌
This is a Bookstore app. Now you can add a book with its **title** and **category**, also you can **delete the book** that you don't want.

#### Thanks for checking 👻

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Murodjon000, congratulations on this milestone :fireworks: Awesome. The following requirements have been met:
- `src/index.js` :100: 
- `App component` :1st_place_medal: 
- `Book component` :fireworks: 
- `BookForm component` :1st_place_medal: 
- `Reduc actions and reducers` :+1: 

However, there a few changes we need to effect in the `BookList component`, let us address the comments below:
- It should connect to Redux store, using the `connect()` function or [Redux hooks](https://react-redux.js.org/api/hooks), and fetches books from the state, let us fix this
- It uses `mapStateToProps` to fetch books from the `store`, let us make this change

[Optional]
- We have 2 lock files, kindly delete one

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by Murodjon000** [comment]
Hi, bro thanks for checking. I used this redux helper in my BooklistContainer in order to save my BookList component cleaner without redux helpers. I think in this way the components will look perfect.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

Thank you for submitting the PR but you need to make changes as requested by the previous CR. 
In case of any confusion reach out to FT CRs. 

Thank you. 

Best, 
Arslan Bisharat.

**Comment by Murodjon000** [comment]
Hi, bro thanks for checking. There is no sense from the last request because I used BooklistContainer to connect redux and react. Using it inside the Booklist component or BookListContiner is same thing.If I am wrong sorry

**Comment by Murodjon000** [comment]
> # Changes Requested 💀
> Thank you for submitting the PR but you need to make changes as requested by the previous CR.
> In case of any confusion reach out to FT CRs.
> 
> Thank you.
> 
> Best,
> Arslan Bisharat.

Hi, bro thanks for checking. There is no sense from the last request because I used BooklistContainer to connect redux and react. Using it inside the Booklist component or BookListContiner is same thing.The aim of using Containers is making redux connectors inside it to make your code clean without mixing it with your component.If I am wrong sorry!

**Comment by bellom** [comment]
> > # Changes Requested 💀
> > Thank you for submitting the PR but you need to make changes as requested by the previous CR.
> > In case of any confusion reach out to FT CRs.
> > Thank you.
> > Best,
> > Arslan Bisharat.
> 
> Hi, bro thanks for checking. There is no sense from the last request because I used BooklistContainer to connect redux and react. Using it inside the Booklist component or BookListContiner is same thing.The aim of using Containers is making redux connectors inside it to make your code clean without mixing it with your component.If I am wrong sorry!

@Murodjon000 Thanks for breaking it down 👍 .
Let's try to be more professional next time in our reply, you can always find a way to explain exactly what you did without sounding unprofessional.

**Review by bellom — APPROVED** [review]
## Hi @Murodjon000  :clap: 

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
