### PR TITLE
Milestone-1

### PR DESCRIPTION
**Pull request by Murodjon000**
### Hi TSE

This is the initial repo for the Bookstore app. The live version link is [this](https://infinite-basin-78643.herokuapp.com/).

**Thanks for checking 👻**

### CODE REVIEW

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Approved :clap:

Hello Developer, :wave:

Thank You for submitting this Pull Request. I am thrilled to inform you that your project is approved now. :clap:

You have done a great job. I like your project. 

**To highlight** 

- [x] You have a descriptive Readme.
- [x] Your Pull Request is nice. Good Job!
- [x] You have deployed your website. Nice!!!
- [x] You are using linters and no error is present. I am happy to see it. 
- [x] Your project has met the minimum technical requirements too. 

In short, I am very excited to see this project and proud of you. 

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

**Comment by arslanbisharat** [comment]
Hello, 

While reviewing your project, I didn't see prop-types in your package.json file and marked your project Request changes. 
I am sorry for the inconvienece. Soon your project will be approved. 
**Please don't submit another Code Review Request. This project will be approved by Dev Team soon.** 

Thank you for understanding. 

Best, 
ARslan Bisharat.

**Comment by Murodjon000** [comment]
Hi Bro no problem

**Comment by arslanbisharat** [comment]
> Hi Bro no problem

Thank You

**Pull request closed without merging**
